# -*- coding: utf-8 -*-
"""경량화 틀입니다~

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkRV5-T9Y-ADvPMr3K0YdCMygGTAq-4L
"""

# 1. 완전 정리 및 최신 설치
!pip uninstall -y transformers accelerate trl
!pip install -U transformers accelerate datasets peft bitsandbytes trl

# 2. 버전 확인
import transformers, accelerate, trl
print("transformers:", transformers.__version__)
print("accelerate:", accelerate.__version__)
print("trl:", trl.__version__)



import transformers
print("Transformers version:", transformers.__version__)

import os
import json
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
    BitsAndBytesConfig,
)
from peft import LoraConfig, get_peft_model

# ✅ CUDA 캐시 초기화
torch.cuda.empty_cache()

# ✅ 설정
BASE_MODEL = "MLP-KTLim/llama-3-Korean-Bllossom-8B"
OUTPUT_DIR = "models/first"
DATA_PATH = "/content/MI_lora_ready_800samples.json"

# ✅ QLoRA (4bit 양자화) 설정
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

# ✅ 토크나이저 로딩
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
tokenizer.pad_token = tokenizer.eos_token

# ✅ 모델 로딩 (4bit, A100 최적화)
base = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
)

# ✅ LoRA 설정
peft_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM"
)
model = get_peft_model(base, peft_config)

# ✅ 데이터 로딩
with open(DATA_PATH, "r", encoding="utf-8") as f:
    raw_data = json.load(f)

dataset = Dataset.from_list(raw_data)

# ✅ 토크나이즈
def tokenize(example):
    return tokenizer(example["text"], truncation=True, padding="max_length", max_length=384)

tokenized_dataset = dataset.map(tokenize, remove_columns=["text"])

# ✅ 학습 설정
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    learning_rate=2e-5,
    logging_steps=10,
    save_strategy="epoch",
    fp16=True,
    save_total_limit=2,
    report_to="none",
)

# ✅ Trainer 구성
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    tokenizer=tokenizer,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

# ✅ 학습
trainer.train()

# ✅ 저장
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("✅ MI 파인튜닝 완료 (A100 + QLoRA 최적화)")

!ls models/first

# Commented out IPython magic to ensure Python compatibility.
# ✅ 1. 필수 패키지 설치
!pip install -q git+https://github.com/huggingface/transformers.git
!pip install -q git+https://github.com/huggingface/peft.git
!pip install -q accelerate sentencepiece

# ✅ 2. llama.cpp 최신 설치
# %cd /content
!git clone https://github.com/ggerganov/llama.cpp.git
# %cd llama.cpp
!mkdir -p build
!cmake -S . -B build -DLLAMA_BUILD_EXAMPLES=ON
!cmake --build build -j
# %cd /content

# ✅ 3. LoRA 결과 디렉토리 설정 (이미 학습된 MI 모델)
lora_path = "/content/models/first"  # ✅ MI 파인튜닝된 디렉토리
merged_path = "/content/merged-first-chat"

# ✅ 4. LoRA 병합 및 FP16 저장
from peft import PeftModel, PeftConfig
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

peft_config = PeftConfig.from_pretrained(lora_path)
base_model_path = peft_config.base_model_name_or_path

base_model = AutoModelForCausalLM.from_pretrained(
    base_model_path,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    low_cpu_mem_usage=True
)

model = PeftModel.from_pretrained(base_model, lora_path)
model = model.merge_and_unload()

model.save_pretrained(merged_path)
tokenizer = AutoTokenizer.from_pretrained(base_model_path)
tokenizer.save_pretrained(merged_path)

# ✅ 5. GGUF로 f16 변환
!python3 /content/llama.cpp/convert_hf_to_gguf.py {merged_path}

# ✅ 6. Q4_K_M 양자화
!./llama.cpp/build/bin/quantize \
  {merged_path}/merged-mi-chat-f16.gguf \
  {merged_path}/merged-mi-chat-q4_k_m.gguf \
  q4_K_M

# ✅ 7. 결과 확인
import os
print("✅ 생성된 GGUF 목록:", os.listdir(merged_path))

# ✅ GGUF로 다시 변환 (정확한 경로, 이름 부여)
!python3 /content/llama.cpp/convert_hf_to_gguf.py /content/merged-first-chat \
  --outfile /content/merged-first-chat/merged-first-8.0B-chat-F16.gguf \
  --outtype f16

# ✅ Q4_K_M 양자화 (올바른 실행 파일명: llama-quantize 사용)
!./llama.cpp/build/bin/llama-quantize \
  /content/merged-first-chat/merged-first-8.0B-chat-F16.gguf \
  /content/merged-first-chat/merged-first-8.0B-chat-Q4_K_M.gguf \
  Q4_K_M

from google.colab import files
files.download('/content/merged-mi-chat/merged-cbt1-chat-q4_k_m.gguf')